namespace Pal.Core.Enums.ActivityLog
{
    public enum LogTransType : int
    {
        Website = 0,
        Users = 1,
        Chat = 2,
        News,
        Slider,
        Team,
        Regions = 6,
        Projects = 7,
        RealEstates = 8,
        Companies = 9,
        Blog = 10,
        Contactus = 11,
        AboutUs = 12,
        Advisors = 13,
        GeneralInfo = 14,
        Advertisements = 15,
        RegionSite = 16,
        RealEstatesBluePrints = 17,
        Customer = 18,
        Language = 19,
        Lookups = 20,
        RatingAndComments = 21,
        Tours = 22,
        Visite = 23,
        OurService = 24,
        Lawyer = 24,
        Tasks = 25,
        Meeting = 26,
        Call = 27,
        Deal = 28,
        Note = 29,
        Reels = 30,
        ReelViews = 31,
        Sales= 32,
    }
}
